packages:
  - 'packages/shared'
  - 'packages/core'
  - 'packages/pwa'
  - 'packages/desktop'
  - 'keynote'
  - 'website'
allowBuilds:
  better-sqlite3: true
  electron: true
  esbuild: true
  win-ca: true
